### ISSUE TITLE
Problem with Halo Sky Tools

### ISSUE THREAD

**Issue by DLDrago** [General-101/Halo-Asset-Blender-Development-Toolset#35]
There's a bug in Halo Sky Tools that says it's looking for a list of floats and finding a color instead.  I'm using Blender 2.93 on Windows 10, and I'm using the default scene with no unit measurement.

You can replicate this by using the default scene and clicking on Generate Sky.

**Comment by General-101** [comment]
Well that's embarrassing. Should be fixed by the time tools drop.

**Comment by General-101** [comment]
@DLDrago Is this an issue with the latest tools?
