### ISSUE TITLE
H3 Design Surfaces

### ISSUE THREAD

**Issue by firebingo** [General-101/Halo-Asset-Blender-Development-Toolset#39]
Exporting design surfaces such as soft_kill as described [here](https://c20.reclaimers.net/h3/level-creation/blender-level-creation-additional-info/#design-surfaces) was broken in commit 8652feeed747daf61421ff2251076e4cfa0d78e0
Setting a material name to something such as `+soft_kill:kill_barrier` causes the material name to be blank in the exported .ass. 
The : separator and a name are required for these materials otherwise tool will fail parsing the material name with a message such as
```
WARNING didn't understand material type '+soft' parsing shader name '+soft_kill'
-ERROR- unable to find shader '_kill' anywhere
```

**Comment by General-101** [comment]
Try release 41. See if that solved your issue.

**Comment by firebingo** [comment]
Release 41 does fix this. Thanks for the fix.
