### ISSUE TITLE
Add ability to export selection for H3 .ASS files

### ISSUE THREAD

**Issue by SamDamDing** [General-101/Halo-Asset-Blender-Development-Toolset#43]
I want to export my Ass files separately and keep them in one blend file. It would help with level design if I could export only the selected object as an ASS.

**Comment by num0005** [comment]
This seems like it would be part of #47, if you don't object I will close this issue in favor of that one.

**Comment by General-101** [comment]
The exporter now drops objects if the collection it belongs to is hidden or excluded. Should get you what you want. I may set something up to automate it in the future.
