### ISSUE TITLE
Add ability to export weighted normals

### ISSUE THREAD

**Issue by csauve** [General-101/Halo-Asset-Blender-Development-Toolset#44]
The exporter currently averages smooth normals on export. However, advanced users may want the ability to export custom weighted normals, something the FBX-JMS pipeline supports. This can be used to achieve [nice results in hard surface modeling](https://i.imgur.com/ikZjE2B.png) with less geometry.

I propose that this be a new ASS/JMS export option grouped with the existing edge split options, but off by default because beginners will definitely shoot themself in the foot with poor normals otherwise.

**Comment by General-101** [comment]
Latest patch now uses loop normals instead of vertex normals so this should no longer be a problem.
