### ISSUE TITLE
Add ability to exclude specific objects when exporting. (suggestion)

### ISSUE THREAD

**Issue by AlexisJonsson** [General-101/Halo-Asset-Blender-Development-Toolset#47]
When working on assets or maps I usually have scale references, other misc objects etc in the scene and it can get a bit tedious hiding/deleting them for every time I do an export.

Allowing the user to add a prefix/suffix symbol like "}" (or any other unused special character) to object names they want excluded from scene would make working on larger scenes/complex assets a bit more easy to manage.

**Comment by num0005** [comment]
I thought there was already a system to do something like this, maybe it needs better documentation. (Or I misremembered)

**Comment by General-101** [comment]
Latest now takes collection exclude/hidden properties into account. Should give you a way to do this.
