### ISSUE TITLE
.wrl importing doesn't seem to be working at all, and there's no error code or anything either.

### ISSUE THREAD

**Issue by TheMindfulMoron** [General-101/Halo-Asset-Blender-Development-Toolset#50]
When attempting to import a .wrl file, nothing happens. No error, no new object or mesh, nothing at all.

**Comment by num0005** [comment]
interesting, could you share the WRL file with us?

**Comment by General-101** [comment]
I asked on Discord and got no example file or response. There's also no example file here. I'm just closing this. If you run into the issue again then please keep the file handy.
