### ISSUE TITLE
Errors importing halo 2 first person weapon animations.

### ISSUE THREAD

**Issue by 0Alastair1** [General-101/Halo-Asset-Blender-Development-Toolset#54]
![2022-05-12 05_05_29-Blender](https://user-images.githubusercontent.com/96997148/167989898-d6b2b8f0-77b1-4255-9057-568b7874f2b5.png)
Importing halo 2 first person weapon animations results in errors. Other halo 2 animations seem to import fine. Animations extracted using bonobo.
I've tried setting the JMS rest positions with correct node names.
I've tried changing JMA versions.
If importing the halo 2 animation with halo ce selected on the import, only the last error message shows.
Unsure if issue with bonobo or blender plugin.

**Comment by General-101** [comment]
I believe I fixed the internal error bit on latest but the circular reference stuff will not change.

**Comment by 0Alastair1** [comment]
example file objects\characters\masterchief\fp\weapons\melee\fp_energy_blade\animations\first_person melee_lunge.JMM
I'm currently extracting from halo 2 classic. ill try tag tool on vista halo 2 and respond back.

**Comment by 0Alastair1** [comment]
all works good using tag tool. thanks.
