### ISSUE TITLE
Issues with Halo Combat Evolved First Person Animations

### ISSUE THREAD

**Issue by josc19** [General-101/Halo-Asset-Blender-Development-Toolset#55]
I've been having some trouble importing Halo's first person animations

3dsmax GBX importer works fine, but throws some really old FBX files I can't really work with.

I am using Halo CE 1.10 files extracted with Refinery 2.3.0, I can't find anything that can extract files from MCC yet after a lot of searching.

![image](https://user-images.githubusercontent.com/105348406/169239149-12a861a9-386e-4b95-9e0d-946ec5edb0e2.png)
Pistol's slider is rotated in a weird way
![image](https://user-images.githubusercontent.com/105348406/169239185-7c6764d1-94ac-4c89-85d9-4acaa072afb7.png)
some issues with the wrists
![image](https://user-images.githubusercontent.com/105348406/169239675-b5fde770-76d0-43ba-9843-48bf39cbd9d5.png)
tried using "fix rotations" but nothing changed
![image](https://user-images.githubusercontent.com/105348406/169239717-9a09ca03-2ade-4129-bfc4-d237c4941f9e.png)
![image](https://user-images.githubusercontent.com/105348406/169239935-ed694dcb-ce08-498f-bd87-f42c9e4c49bf.png)
not sure if this also happened in the original engine as its hard to see with dark textures.
[issue.zip](https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/files/8726871/issue.zip)

Let me know if I'm missing a step, I can't seem to find documentation on doing Halo CE assets.

**Comment by josc19** [comment]
Forgot to mention, issue.zip is the final result after importing both jms files.

**Comment by General-101** [comment]
Seems like the default pose script is doing something wrong. Looking into it.

For now you can set up the skeleton manually and it should work fine from there.

**Comment by General-101** [comment]
Should be fixed in latest
