### ISSUE TITLE
When exporting JMS all meshes get merged into one

### ISSUE THREAD

**Issue by Kolshgamer** [General-101/Halo-Asset-Blender-Development-Toolset#56]
I've been trying to model my vehicle with multiple meshes because I saw the warthog with multiple meshes
But when I export the JMS file, I come to find out that all meshes were made into one meshed named "__unnamed".
How do I stop this from happening? I'm modding for Halo CE (Custom Edition)

**Comment by General-101** [comment]
You have to assign a region to the faces of your mesh through the Halo regions menu. Late but eh. Consider joining either the Halo Mods Discord or Halo Modding Reclaimers for more assistance

https://discord.gg/halo-modding-reclaimers-228263208299790338

https://discord.gg/halo-mods-615301822474878977
