### ISSUE TITLE
[Bug] Material Naming Issue

### ISSUE THREAD

**Issue by Dasfonia** [General-101/Halo-Asset-Blender-Development-Toolset#57]
Editing materials' names from within the "Scene Collection" in Blender's UI does not update the name that is read upon exporting a JMS file for Halo 2 (and maybe other asset types/games, however, that's untested).  A band-aid fix for the aforementioned issue you must re-edit the affected material name(s) in the "Material Properties" section in Blender's UI.

Steps To Reproduce:

1) tool extract-render-data scenarios\objects\solo\earthcity\signage\sign_road_signal\sign_road_signal
2) Import the !extracted\sign_road_signal\sign_road_signal.jms into Blender
3) Go to the Scene Collection side-bar UI area in Blender and expand Armature->sign_road_signal->sign_road_signal and edit two materials' names from: **signage_glass!=** to **ob signage_glass!=** and **signage_signal!=** to **ob signage_signal!=** (you can just skip doing the import fix-ups here because it doesn't affect the incorrect outcome we're looking for here)
4) Export the Halo 2 JMS to data\scenarios\objects\solo\earthcity\signage\sign_road_signal\render (back up the original .render_model tag!)
5) tool render scenarios\objects\solo\earthcity\signage\sign_road_signal
6) Watch it not correctly find the two shaders during the render command
7) Go back to Blender and go to the Material Properties UI Tab in the sidebar, change one character in each of those material names, and then change it back, press enter (final names should still be **ob signage_glass!=** and **ob signage_signal!=**).
8) Export again
9) Render again, fixed!

**Comment by General-101** [comment]
This might be a legitimate bug with Blenders evaluated_depsgraph_get() function. Need to look into this more. If you disable the apply modifiers settings then this isn't a thing but obv that's not ideal.

**Comment by General-101** [comment]
https://developer.blender.org/T100375

**Comment by General-101** [comment]
The issue was confirmed and should be solved on the latest alpha version of Blender. See the above ticket

**Comment by General-101** [comment]
This has been fixed in the latest Blender release. Closing.
