### ISSUE TITLE
Instanced geometry not importing correctly

### ISSUE THREAD

**Issue by Fadervish** [General-101/Halo-Asset-Blender-Development-Toolset#63]
When importing some H2 bsps (haven't tested all of them but district and sacred icon are affected), some of the instanced geo gets offset randomly.

**Comment by austinbaccus** [comment]
I'm having this issue as well. Some of the geometry is offset at random or missing entirely. For isntance, the big spinning wheel on Zanzibar is placed on the beach instead of the middle of the map, and Zanzibar's building is now inside the big spinning wheel and rotated 90 degrees on its side.

**Comment by austinbaccus** [comment]
![image](https://user-images.githubusercontent.com/10345834/203216615-46440d0d-aa8b-4e3c-be3c-b55892ce0d69.png)
