### ISSUE TITLE
Animated scale not being imported properly

### ISSUE THREAD

**Issue by SPARTAN-277** [General-101/Halo-Asset-Blender-Development-Toolset#66]
When importing a JMA/JMM file that has scale keyframes baked into the animation, those keyframes are not imported into Blender. Animated scale keyframes are successfully _exported_, however, since manually making custom scale keyframes and exporting that to the game appears fine. The only issue is importing the scale animation from an existing JMA/JMM, even custom animations exported from Blender.

This issue is evident with Halo 2 cinematic animations, such as the In Amber Clad at the start of Delta Halo. Every animation it has in the cutscene uses various amounts of scale, all of which scale the model down a lot since the actual model is huge. However, when the model/animations are imported into Blender, that scale isn't imported, so the model stays unreasonably large in comparison to the original cutscene.

**Tested with the following model (which was extracted with H2 Tool in the Halo 2 MCC Editing Kit)**:
**Tag**: tags\objects\cinematics\human\inamberclad\inamberclad.render_model
**File**: inamclad.jms

**Tested with the following animations (which were extracted with TagTool from Halo 2 Xbox's 05a_deltaapproach.map)**:
**Tag**: tags\objects\cinematics\human\inamberclad\x05\x05.jmad
**File**: iac_01.JMM
**File**: iac_03.JMM
**File**: iac_05.JMM
**File**: iac_07.JMM
**File**: iac_08.JMM

**Comment by General-101** [comment]
I might have a fix for this. I'll drop something for you to try out in a bit.

**Comment by General-101** [comment]
Fixed in 3915783
