### ISSUE TITLE
[Request] Custom Checksum per .blend project

### ISSUE THREAD

**Issue by YamashiroKai** [General-101/Halo-Asset-Blender-Development-Toolset#67]
Having to manually edit the checksum every time you export something is tedious if you are rapidly testing new iterations. A feature to set the checksum when exporting would be great.

**Comment by General-101** [comment]
I will not have code to set random checksums that don't match the output skeleton. There is an issue in the code at the moment that won't sort skeletons the exact same way as the original toolset that is being worked on. The code to generate the checksum though is accurate.
