### ISSUE TITLE
Importing some animations with "Fix Rotations" checked can result in a corrupted import

### ISSUE THREAD

**Issue by 77Mynameislol77** [General-101/Halo-Asset-Blender-Development-Toolset#71]
The biped was the reach "spartan.biped", using it's FP animations of the needler.

Tagtool was used in extracting said animations, and i used the "Batch Anim Converter" built into the toolkit to convert them into the halo 3 animation format.

This is how the included animation looks when imported without "Fix Rotations" checked

![image](https://user-images.githubusercontent.com/35608876/189212007-9920c721-fbdb-40d0-82a7-0c0222e16ec5.png)

And this is how the included animation looks when imported with "Fix Rotations" checked

![image](https://user-images.githubusercontent.com/35608876/189212094-055be163-3cab-4d53-95be-51e7dce8c829.png)

Here's an included example animation to test it with.

[example-animation.zip](https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/files/9530264/example-animation.zip)

**Comment by General-101** [comment]
I think I have a fix for this. I'll upload something later

**Comment by General-101** [comment]
I assume I fixed this. Closing
