### ISSUE TITLE
Internal error: <class 'AttributeError'>('Mesh' object has no attribute 'region_list')

### ISSUE THREAD

**Issue by JKeeey** [General-101/Halo-Asset-Blender-Development-Toolset#77]
I keep trying to export a custom model into .JMS format for CE. When I export without markers it exports with no issue, but when I try to export markers it gives me
Internal error: <class 'AttributeError'>('Mesh' object has no attribute 'region_list')
Both the markers and the model mesh have the same Face Maps and Halo Regions.
I've even tried re-exporting imported gbxmodels that have been untouched (markers and all) and it gives me the same error.
Attached is a traceback file from the crash report: 
[traceback.txt](https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/files/12328585/traceback.txt)

**Comment by General-101** [comment]
This should be fixed but make a new issue if it isn't
