### ISSUE TITLE
Halo Regions Screwed UP!

### ISSUE THREAD

**Issue by SargentZero** [General-101/Halo-Asset-Blender-Development-Toolset#82]
Someone had the bright idea to replace Face Maps with Halo Regions, which NOBODY asked for. This screwed up basic operations in blender for regions. If you accidentally delete a region within "Halo Regions," you can't undo\redo it back. If you merge (Ctrl-J) 2 objects with multiple regions for each object, the first selected objects's "Halo Regions" will replace ALL the regions in the second object. This was already working normally for Face maps, now working with halo regions is broken. Fix this please, this is very inconvenient. For now I will downgrade this toolset

**Comment by SargentZero** [comment]
For anyone working with regions use version 144 for now, that one uses the facemaps instead halo regions

**Comment by AlexisJonsson** [comment]
Blender 4.0 deprecated face maps so they had to create an alternate solution.

**Comment by General-101** [comment]
The sad thing is I agree with pretty much everything you said. Wish I could just undo it. There is a operator helper or merging objects while keeping regions intact in the tools menu. Otherwise stay on Blender versions with facemap support ig.

Closing
