### ISSUE TITLE
When importing ass, mesh names are all identical

### ISSUE THREAD

**Issue by dt192** [General-101/Halo-Asset-Blender-Development-Toolset#85]
All meshes are named `object_` then the number of materials in the ass.

Guardian for example has 93 materials, all meshes are named `object_93`

![2024-02-12_11-56](https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/assets/2612048/07f3fba6-83a5-4fa4-9994-b2914fa02ebe)

Looks like 146 should be an enumerate as with materials

https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/blob/e8d2270f9cc8653f3a6fa88a2451b090412ead25/io_scene_halo/file_ass/build_scene.py#L135-L147

**Comment by General-101** [comment]
Fixed in latest
