### ISSUE TITLE
Water Surface flag has no effect (H3 ass)

### ISSUE THREAD

**Issue by dt192** [General-101/Halo-Asset-Blender-Development-Toolset#86]
Checking the Water Surface box makes no change to the output ass file.

![2024-02-19_17-07](https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/assets/2612048/8cd31a16-962d-40ae-8034-a4281cacb2cb)

**Comment by General-101** [comment]
Pretty sure both checked items in the image go unused. Removed them in 92f10ae
