### ISSUE TITLE
Mask options still not working as expected

### ISSUE THREAD

**Issue by dt192** [General-101/Halo-Asset-Blender-Development-Toolset#87]
The instances here still get exported.

![2024-03-03_11-16](https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/assets/2612048/3953a31d-7097-4256-8570-d072cac31007)
![2024-03-03_11-17](https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/assets/2612048/f880f226-c2ea-4e6d-b50a-bae55c6d9702)

Another issue... if I check Export Hidden Geometry I get this error
![2024-03-03_11-23](https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/assets/2612048/1167bf09-0b1d-4e4f-ab4a-6694c7d25802)

**Comment by General-101** [comment]
Should be fixed in 9711900
