### ISSUE TITLE
Objects using inverse scaling (mirroring) throw non uniform error. H3 ASS

### ISSUE THREAD

**Issue by dt192** [General-101/Halo-Asset-Blender-Development-Toolset#88]
Objects using inverse scaling (mirroring) throw non uniform error.
These all share their origin in the centre and are just mirrored across it. They render fine in game.
Having a page full of these on export makes it more difficult to see valid warnings.

![2024-02-29_17-30](https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/assets/2612048/2b833339-2622-4694-a830-bc3f57625015)

**Comment by General-101** [comment]
I can't seem to repo this? I assume fixed but reopen if the issue happens. If it does happen please provide an example blend.
