### ISSUE TITLE
Skylights being written out of order causing bad light bakes JMS

### ISSUE THREAD

**Issue by dt192** [General-101/Halo-Asset-Blender-Development-Toolset#89]
The internal order of skylights can get jumbled by blender leading to the lights being written to the JMS in the wrong order, which in turn leads to bad light bakes.

The objects are still in the right order in the outliner, but just stored out of order in the api. I assume the jms writes just writes them out in the order it finds them in the array of objects.

Someone else was having the same issue here: https://discord.com/channels/228263208299790338/1078916642102325269/1078916642102325269

Pics show before and after me fixing the order.
![2024-03-03_12-35](https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/assets/2612048/09f4c7c2-70c1-4abd-9608-23361c727888)
![2024-03-03_12-52](https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/assets/2612048/f62345ed-8f04-48cd-9522-5bb2b16c365b)

Something else I noticed while trying to troubleshoot the above was that if you import then export the Avalanche sky, the last skylight gets messed up, I assume due to the values being negative.
![2024-03-03_13-04](https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/assets/2612048/45d1ed8b-ac7e-42c0-a6fb-ae08e6cf3ce6)

**Comment by General-101** [comment]
This should have be solved. Make another issue is it isn't
