### ISSUE TITLE
Blender 4.1 error exporting H3 ass

### ISSUE THREAD

**Issue by dt192** [General-101/Halo-Asset-Blender-Development-Toolset#90]
```
File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\io_scene_halo\file_ass\process_scene.py", line 447, in process_scene
    evaluted_mesh.calc_normals_split()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Internal error: <class 'AttributeError'>('Mesh' object has no attribute 'calc_normals_split')
```

**Comment by fable-law-458** [comment]
I'm having the same issue when trying to export .jms files as well.

**Comment by General-101** [comment]
Should be fixed on latest. Reopen if it isn't.

**Comment by L9M2** [comment]
Latest 247 build seemed to have broken exporter for ASS files in Blender 4.1.1. Compiling the level with tool throws
-FATAL- mesh definition vertex normal invalid: (0.000000, 0.000000, 0.000000)
-FATAL- couldn't parse definition #0
Downgrading to Blender 4.0 and using Build 190 (The build for Blender 4.0 initial) and exporting the same level doesn't produce this compiling issue.

**Comment by jackrabbit72380** [comment]
I'm getting the error as well... Internal error: <class 'AttributeError'>('Mesh' object has no attribute 'calc_normals_split')
