### ISSUE TITLE
Blender crashing when trying to edit "Mesh" portion of extracted structure - Halo 2.

### ISSUE THREAD

**Issue by SMGgoPrrrrrr** [General-101/Halo-Asset-Blender-Development-Toolset#94]
Halo 2 map extracted with newest h2 tools, newest blender and newest halo asset blender tools. Blender closes when changing to edit mode on "mesh" portion of the structure. 
Version halo-asset-blender-toolset-full-v143@c228c7f works just fine on older blender version that is.

**Comment by General-101** [comment]
what level?

**Comment by SMGgoPrrrrrr** [comment]
:o backwash

**Comment by SMGgoPrrrrrr** [comment]
Tried opening a previous extraction with newest asset tools and blender and it didnt crash. The previous extraction however has all vertices connected unlike the new extraction not that i think it matters but still wanted to mention this.

**Comment by General-101** [comment]
https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/releases/tag/245
Try that

**Comment by SMGgoPrrrrrr** [comment]
I got this message
![Untitleda](https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/assets/98787612/0991125a-0445-490d-85f4-eb9b78ecefec)

**Comment by SMGgoPrrrrrr** [comment]
Ill just use an older ver no big deal

**Comment by General-101** [comment]
I haven't been ignoring this tbc. It will just take me a bit to get around to it. Handling some other stuff. I'll reopen when I have more time.

**Comment by SMGgoPrrrrrr** [comment]
Yeah np.
