### ISSUE TITLE
I'm new to modding and I come across this error does anyone know how to fix it?

### ISSUE THREAD

**Issue by DrBuzzsaw** [General-101/Halo-Asset-Blender-Development-Toolset#97]
![Screenshot 2024-07-04 160208](https://github.com/General-101/Halo-Asset-Blender-Development-Toolset/assets/174747869/656ae82e-bddb-4fc6-b8eb-8849c48b735c)

**Comment by General-101** [comment]
Update to Blender 4.1 or later

**Comment by DrBuzzsaw** [comment]
Thanks
