### ISSUE TITLE
QUA export exports all armatures regardless of whether they are selectable or not

### ISSUE THREAD

**Issue by EnashMods** [General-101/Halo-Asset-Blender-Development-Toolset#99]
I have a scene with some armatures (ik control rigs) that I do not want included in the qua, I'd like them to not be exported when selectable under visibility is not ticked

**Comment by General-101** [comment]
I'll see about adding the hidden/render visibility setup later.

**Comment by General-101** [comment]
Latest should work for this. Please confirm that the options are working as you expect.
